### ISSUE TITLE
releases

### ISSUE THREAD

**Issue by 030** [jtyr/ansible-qpid_cpp_server#2]

**Comment by jtyr** [comment]
Do you mean tag the repo?

**Comment by 030** [comment]
Yes. Could you create a tag so that version control is possible?

**Comment by jtyr** [comment]
Tag created.

**Comment by 030** [comment]
Thank you. What about semantic versioning? E.g. 1.0.0 instead of 1.0?

**Comment by jtyr** [comment]
Too many numbers. Even 1.0 is overkill.
